"""Everything the site says, in one place.

Every number rendered inside a [data-claims] section must appear in a CLAIMS value
(tests/test_site.py::test_t7_rendered_numbers_are_claims). Refresh the live ones with
scripts/refresh_claims.py before publishing.
"""

AS_OF = "2026-09-15"

PROFILE = {
    "name": "Okechukwu Wisdom",
    "headline": "Research Engineer · 3 EigenCloud prizes · 4th of 71 on ecdsa.fail",
    "description": "Research Engineer in crypto (prediction markets) and AI (agents).",
    "bio": [
        "Named author on an arXiv quantum computing paper at 19. Most of my engineering is in crypto (prediction markets) and AI (agents).",
        "At Free Systems Lab I research AI agents, especially swarms of agents, and follow whatever questions pull me in. I built Model Card Explorer there, which found that 90% of frontier benchmarks are reported by only one lab. On ecdsa.fail I placed 4th of 71 solvers by total score reduction, and that work put my name on the paper.",
        "Things I've shipped: bob is alive, an AI that pays for its own compute inside a TEE, took 1st and $3,000 in the EigenCompute track at the Synthesis Hackathon. Mind Agent and EigenBox, two developer tools with 1,095 npm downloads. A zk-SNARK shielded pool design for Plasma whose launch posts passed 80K views.",
        "Open to joining Eigen Labs as an engineer anytime I get an offer letter. Also: on the side I'm building Sturbon, free counseling and mentors for African teenagers, accepted into 2 funds whose pools total $42K+.",
    ],
    "location": "Kigali, RW",
    "photo": "/assets/me.jpg",
    "links": [
        {"label": "GitHub", "href": "https://github.com/owizdom"},
        {"label": "X", "href": "https://x.com/oxwizzdom"},
        {"label": "LinkedIn", "href": "https://www.linkedin.com/in/wisdom-o-427222398/"},
        {"label": "Substack", "href": "https://parallelresearch.substack.com/"},
        {"label": "Flashbots Forum", "href": "https://collective.flashbots.net/u/wisdom/summary"},
        {"label": "Telegram", "href": "https://t.me/oxwizzdom"},
        {"label": "Email", "href": "mailto:okechukwuwisdom016@gmail.com"},
    ],
}

NOW = [
    {"org": "Free Systems Lab", "href": "https://freesystems.net/", "role": "Research Fellow",
     "years": "2026 to now", "logo": "/assets/experience/freesystems.png",
     "note": "Research on AI agents, including Sticky Fingers, a controlled study of whether payment rails stop a hijacked agent from moving money, Model Card Explorer and the Free Systems Model Cards."},
    {"org": "Eigen Labs (EigenCloud)", "href": "https://www.eigenlabs.org", "role": "Open-source contributor",
     "years": "2026 to now", "logo": "/assets/experience/eigenlabs.png",
     "note": "Apps and tooling on EigenCompute (EigenBox, bob is alive, vanta) and contributions to Darkbloom, the private inference network on idle Macs."},
    {"org": "Sturbon", "href": "https://sturbon.vercel.app/", "role": "Founder",
     "years": "now", "logo": "/assets/experience/sturbon.svg",
     "note": "Free counseling and mentors for African teenagers who feel alone. Live in two Nigerian states, and accepted into 2 funds whose pools total $42K+."},
]

BEFORE = [
    {"org": "Bento.fun", "href": "https://bento.fun", "role": "Software Engineer Intern",
     "years": "Jun 2026 to Aug 2026", "logo": "/assets/experience/bento.png",
     "note": "Built the Bento Agent Kit, an MCP server for prediction markets, and the resolution and settlement engine."},
    {"org": "Decentralised.co", "href": "https://www.decentralised.co/", "role": "Research Intern",
     "years": "Aug 2025 to Nov 2025", "logo": "/assets/experience/decentralised.png",
     "note": "Charts and threads on agent payments, neobanks and savings rates for a newsletter with 24,000+ subscribers."},
    {"org": "Parallel Research", "href": "https://parallelresearch.substack.com/", "role": "Founder and Head of Research",
     "years": "Nov 2024 to Oct 2025", "logo": "/assets/experience/parallel.png",
     "note": "35 posts on Solana internals, scaling, MEV, stablecoins and TEEs, including the Plasma shielded pool design."},
    {"org": "Shoal Research", "href": "https://www.shoal.gg/", "role": "Research Analyst",
     "years": "Sep 2024 to Jul 2025", "logo": "/assets/experience/shoal.png",
     "note": "7 deep-dive reports, including zkTLS, Fairblock and Sonic SVM, for a list of 2.4K+ subscribers."},
    {"org": "2077 Research", "href": "https://2077.xyz/", "role": "Infrastructure research intern",
     "years": "May 2024 to Jan 2025", "logo": None, "mark": "77",
     "note": "Infrastructure research and advanced tutorials on Ethereum improvement proposals and rollups."},
    {"org": "Coinbase Developer Platform", "href": "https://www.coinbase.com/developer-platform", "role": "User Research Contributor",
     "years": "Aug 2024 to Sep 2024", "logo": "/assets/experience/coinbase.png",
     "note": "Built against Paymaster and OnchainKit and reported the integration failures to engineering."},
]

EXPERIENCE = [{"role": r["role"], "org": r["org"], "years": r["years"]} for r in NOW + BEFORE]

# Order matters: the three Eigen placings first, then EigenBox and Mind Agent (T8).
PROJECTS = [
    {"name": "bob is alive", "mark": "B", "face": "amber",
     "tagline": "An artist that has to earn its keep",
     "badge": "1st, Best Use of EigenCompute, Synthesis Hackathon, $3,000",
     "desc": "An autonomous organism inside an EigenCompute TEE. It reads biology news, makes art, and sells NFTs and trades on the Starknet Sepolia testnet to pay for its own compute. If its balance hits zero, it dies.",
     "install": None,
     "tags": ["EigenCompute", "Intel TDX", "Starknet Sepolia"],
     "links": [{"label": "Live", "href": "https://bob-is-alive.vercel.app"},
               {"label": "GitHub", "href": "https://github.com/owizdom/bobIsAlive"},
               {"label": "EigenCloud feature", "href": "https://blog.eigencloud.xyz/ai-gent-hackathon-sythesis/"}]},
    {"name": "swarm mind", "mark": "S", "face": "violet",
     "tagline": "Agents that can't copy each other",
     "badge": "3rd, EigenCloud Open Innovation Challenge",
     "desc": "Three AI agents reason over live NASA data in isolation, commit their findings to EigenDA before seeing each other's work, then reveal, so anyone can check they reached the same answer independently.",
     "install": None,
     "tags": ["Multi-agent", "EigenDA", "TEE"],
     "links": [{"label": "GitHub", "href": "https://github.com/owizdom/swarm-mindv2"},
               {"label": "Eigen Labs feature", "href": "https://www.eigenlabs.org/blog/five-ai-agents-that-can-prove-theyre-honest/"}]},
    {"name": "vanta", "mark": "V", "face": "lime",
     "tagline": "A lender whose reasoning is attested",
     "badge": "4th, Eigen Internal Private Preview Program",
     "desc": "A council of AI lending agents that underwrites USDC loans against Polymarket positions from inside a TEE, with each loan decision and the key that signs it bound to one attestation.",
     "install": None,
     "tags": ["Prediction markets", "TEE", "USDC"],
     "links": [{"label": "Live", "href": "https://vanta-app.vercel.app"},
               {"label": "Attestation", "href": "https://verify.eigencloud.xyz/app/0x95F2AB29fAa9A4C834B06B0514428d63C6e0E80d"},
               {"label": "GitHub", "href": "https://github.com/owizdom/vanta"},
               {"label": "Eigen Labs feature", "href": "https://www.eigenlabs.org/blog/your-ai-agent-could-be-lying-these-15-cant/"}]},
    {"name": "EigenBox", "mark": "E", "face": "blue",
     "tagline": "Ship an Eigen-verified app in any language",
     "badge": "382 npm downloads",
     "desc": "A TEE-side gateway fronts your app on EigenCompute and signs every response, so your own code needs no Eigen-specific lines.",
     "install": "npx create-eigenbox my-app",
     "tags": ["EigenCompute", "Go", "npm"],
     "links": [{"label": "GitHub", "href": "https://github.com/owizdom/eigenbox"},
               {"label": "npm", "href": "https://www.npmjs.com/package/create-eigenbox"}]},
    {"name": "Mind Agent", "mark": "M", "face": "slate",
     "tagline": "Issues triaged before you open the laptop",
     "badge": "713 npm downloads",
     "desc": "A background agent that watches GitHub orgs and repos for new issues, gathers the relevant code, opens a branch and queues each issue for you to fix.",
     "install": "npm i -g @parallel-labs/mind-agent",
     "tags": ["Developer tool", "TypeScript", "npm"],
     "links": [{"label": "GitHub", "href": "https://github.com/owizdom/mind-agent"},
               {"label": "npm", "href": "https://www.npmjs.com/package/@parallel-labs/mind-agent"}]},
    {"name": "Sturbon", "mark": "S", "face": "rose",
     "tagline": "Someone who stays",
     "badge": "Accepted into 2 funds with $42K+ in pools",
     "desc": "Free counseling and mentors for African teenagers who feel alone. Self-funded and live in two Nigerian states.",
     "install": None,
     "tags": ["Mental health", "Africa"],
     "links": [{"label": "Live", "href": "https://sturbon.vercel.app/"},
               {"label": "Fund page", "href": "https://artizen.fund/index/p/sturbon-mental-health-for-african-youth?season=7"}]},
    {"name": "Model Card Explorer", "mark": "M", "face": "green",
     "tagline": "Who discloses which benchmarks",
     "badge": "90% of benchmarks reported by one lab",
     "desc": "Reads 90 public model cards from 6 frontier labs. Of 689 distinct benchmarks, 90% are reported by only one lab. Built at Free Systems Lab.",
     "install": None,
     "tags": ["AI evaluation", "Research"],
     "links": [{"label": "Live", "href": "https://modelcards.net"},
               {"label": "GitHub", "href": "https://github.com/owizdom/ai-research-model-cards"}]},
    {"name": "Free Systems Model Cards", "mark": "F", "face": "indigo",
     "tagline": "AI's frontier as trading cards",
     "badge": "First edition, 28 cards from 9 labs",
     "desc": "Frontier models turned into trading cards built from 541 distinct published tests, so you can compare models and spot gaps in their safety reporting. Written up with James Campsie and Andy Hall.",
     "install": None,
     "tags": ["AI evaluation", "Free Systems Lab"],
     "links": [{"label": "Live", "href": "https://modelcards.freesystems.net/"},
               {"label": "Write-up", "href": "https://freesystems.substack.com/p/model-cardscollect-em-all"}]},
    {"name": "rootward", "mark": "R", "face": "stone",
     "tagline": "Static auditor for protocols on cloud TEEs",
     "badge": "v0.2.1, open source",
     "desc": "Audits Web3 protocols that run on cloud TEEs from their source, before anything is deployed.",
     "install": None,
     "tags": ["Security", "TEE", "Python"],
     "links": [{"label": "GitHub", "href": "https://github.com/owizdom/rootward"}]},
    {"name": "Gatekeeper", "mark": "G", "face": "teal",
     "tagline": "Rules for agent-authored pull requests",
     "badge": "Open source, 168 tests",
     "desc": "One .gatekeeper.yml decides which agent-authored pull requests merge on their own and which wait for a human.",
     "install": None,
     "tags": ["Developer tool", "AI agents"],
     "links": [{"label": "GitHub", "href": "https://github.com/owizdom/gatekeeper"}]},
]

WRITING = [
    {"title": "Model cards...collect 'em all?",
     "href": "https://freesystems.substack.com/p/model-cardscollect-em-all",
     "venue": "Free Systems, with James Campsie and Andy Hall", "when": "Sep 2026",
     "note": "The first edition of the Free Systems Model Cards, covering 28 recent models."},
    {"title": "Confidential Stablecoin Transfers on Plasma: A zk-SNARK-Based Shielded Pool Design",
     "href": "https://parallelresearch.substack.com/p/confidential-stablecoin-transfers",
     "venue": "Parallel Research", "when": "Jun 2025",
     "note": "An open-source design for Plasma. The launch posts drew 42.4K and 38K views on X."},
    {"title": "Deep dive into EigenCompute internals",
     "href": "https://x.com/oxwizzdom/status/2050988506197950467",
     "venue": "X Article, quoted by EigenCloud", "when": "May 2026",
     "note": "TDX, attestations, KMS, app IDs and verifiable builds. 7.7K views, and EigenCloud's quote post of it drew 4,375."},
    {"title": "MEV - A Deep Dive",
     "href": "https://parallelresearch.substack.com/p/mev-a-deep-dive",
     "venue": "Parallel Research", "when": "Sep 2025",
     "note": "10,774 words."},
    {"title": "The 6.99% without PBS",
     "href": "https://collective.flashbots.net/t/the-6-99-without-pbs/5283",
     "venue": "Flashbots Forum", "when": "Sep 2025",
     "note": "401 views. My forum posts have 1,234 views in total."},
    {"title": "zkTLS: Verifiable Data Composability",
     "href": "https://www.shoal.gg/p/zktls-verifiable-data-composability",
     "venue": "Shoal Research", "when": "Mar 2025", "note": ""},
    {"title": "Sonic SVM: The HyperGrid Future, Powering TikTok App Layer",
     "href": "https://www.shoal.gg/p/sonic-svm",
     "venue": "Shoal Research", "when": "Jan 2025", "note": ""},
    {"title": "CUDIS: The AI DePIN Smart Ring Democratizing Health Data on Solana",
     "href": "https://www.shoal.gg/p/cudis-the-ai-depin-smart-ring-democratizing",
     "venue": "Shoal Research", "when": "Jul 2025", "note": ""},
    {"title": "Fairblock: Incorruptible Markets and Confidential Stablecoin Rails",
     "href": "https://www.shoal.gg/p/fairblock-incorruptible-markets-and",
     "venue": "Shoal Research", "when": "May 2025", "note": ""},
    {"title": "Fragmetric: Unlocking Composable Restaking with Solana's Token-2022 Standard",
     "href": "https://www.shoal.gg/p/fragmetric-unlocking-composable-restaking",
     "venue": "Shoal Research", "when": "May 2025", "note": ""},
    {"title": "zkPass: Enabling Verifiable Data Composability",
     "href": "https://www.shoal.gg/p/zkpass-enabling-verifiable-data-composability",
     "venue": "Shoal Research", "when": "Mar 2025", "note": ""},
    {"title": "Enso Network: The \"Shortcut\" To Your On-Chain Operations",
     "href": "https://www.shoal.gg/p/enso-network-shortcuts",
     "venue": "Shoal Research", "when": "Mar 2025", "note": ""},
    {"title": "Betting on TEEs: The Infrastructure Thesis for zkSync's Market Edge",
     "href": "https://parallelresearch.substack.com/p/betting-on-tees-the-infrastructure",
     "venue": "Parallel Research", "when": "Jun 2025", "note": ""},
]

RECOGNITION = [
    {"text": "Named author, ECDSA.Fail: Open Autoresearch for Optimizing Elliptic-Curve Point Addition in Shor's Algorithm",
     "href": "https://arxiv.org/abs/2609.09582", "venue": "arXiv", "when": "2026"},
    {"text": "4th of 71 solvers by total score reduction", "href": "https://ecdsa.fail",
     "venue": "ecdsa.fail", "when": "2026"},
    {"text": "1st, Best Use of EigenCompute (bob is alive)",
     "href": "https://blog.eigencloud.xyz/ai-gent-hackathon-sythesis/",
     "venue": "Synthesis Hackathon", "when": "2026"},
    {"text": "3rd, Open Innovation Challenge (swarm mind)", "href": "https://www.eigenlabs.org/blog/five-ai-agents-that-can-prove-theyre-honest/",
     "venue": "EigenCloud", "when": "2026"},
    {"text": "4th, Internal Private Preview Program (vanta)", "href": "https://www.eigenlabs.org/blog/your-ai-agent-could-be-lying-these-15-cant/",
     "venue": "Eigen Labs", "when": "2026"},
    {"text": "From Qbasic to Solidity: How Okechukwu Wisdom is Creating Impact in Blockchain and Beyond",
     "href": "https://rubiestech.org/from-qbasic-to-solidity-how-okechukwu-wisdom-is-creating-impact-in-blockchain-and-beyond/",
     "venue": "Rubies Technologies", "when": "2024"},
]

STACK = [
    {"group": "Languages", "items": ["Python", "TypeScript", "Rust", "Go", "C", "Solidity"]},
    {"group": "Trusted compute", "items": ["Intel TDX", "EigenCompute", "Remote attestation"]},
    {"group": "Web and data", "items": ["Next.js", "FastAPI", "PostgreSQL", "Redis"]},
    {"group": "Infrastructure", "items": ["Docker", "Kubernetes", "Linux", "GitHub Actions"]},
]

CLAIMS = [
    {"id": "ecdsafail-rank", "value": "4th of 71 promoted solvers by cumulative reduction, three promoted submissions",
     "source": "ecdsafail submissions --all (CLI v2026.08.21-4)", "as_of": AS_OF},
    {"id": "ecdsafail-paper", "value": "arXiv:2609.09582, named author", "source": "https://arxiv.org/abs/2609.09582", "as_of": "2026-09-12"},
    {"id": "age", "value": "19", "source": "Wisdom", "as_of": AS_OF},
    {"id": "modelcards", "value": "90 model cards, 6 frontier labs, 689 distinct benchmarks, 90% reported by one lab",
     "source": "https://modelcards.net", "as_of": AS_OF},
    {"id": "shoal-reports", "value": "7 reports bylined wisdom/wizzdom, 2025-01-30 to 2025-07-17", "source": "https://www.shoal.gg/api/v1/archive (all 76 posts, distinct ids)", "as_of": AS_OF},
    {"id": "shoal-subscribers", "value": "2.4K+ subscribers", "source": "https://www.shoal.gg/about (freeSubscriberCountOrderOfMagnitude)", "as_of": AS_OF},
    {"id": "parallel-posts", "value": "35 posts, 2024-11-30 to 2025-10-07", "source": "https://parallelresearch.substack.com/api/v1/archive", "as_of": AS_OF},
    {"id": "plasma-launch-views", "value": "42.4K and 38K views, 80K combined (42,410 + 38,068)",
     "source": "https://x.com/oxwizzdom/status/1934281539413590395 and https://x.com/oxwizzdom/status/1934663499352879491", "as_of": AS_OF},
    {"id": "npm-downloads", "value": "1,095 total: create-eigenbox 382, @parallel-labs/mind-agent 713",
     "source": "https://api.npmjs.org/downloads/range/ (create-eigenbox 2026-06-01:2026-09-15, @parallel-labs/mind-agent 2026-01-20:2026-09-15)", "as_of": AS_OF},
    {"id": "2077-dates", "value": "May 2024 to Jan 2025", "source": "Wisdom (self-reported, 15 Sep 2026)", "as_of": AS_OF},
    {"id": "freesystems-model-cards", "value": "first edition covering 28 recent models; 476,000 words across 22 model and system cards", "source": "https://freesystems.substack.com/p/model-cardscollect-em-all", "as_of": AS_OF},
    {"id": "freesystems-model-cards-site", "value": "first edition, 28 cards from 9 labs; 541 distinct tests", "source": "https://modelcards.freesystems.net/", "as_of": AS_OF},
    {"id": "eigen-prizes", "value": "3 EigenCloud prizes", "source": "Wisdom's prize announcements and payout records (held privately)", "as_of": AS_OF},
    {"id": "eigen-placings", "value": "1st Best Use of EigenCompute $3,000; 3rd Open Innovation Challenge; 4th Internal Private Preview Program",
     "source": "Wisdom's prize announcements and payout records (held privately); featured in https://blog.eigencloud.xyz/ai-gent-hackathon-sythesis/, https://www.eigenlabs.org/blog/five-ai-agents-that-can-prove-theyre-honest/, https://www.eigenlabs.org/blog/your-ai-agent-could-be-lying-these-15-cant/", "as_of": AS_OF},
    {"id": "sturbon-artizen", "value": "curated into 2 Season 7 funds: Community Network Fund ($14,609 total), Technopenuriaphobia Fund for Human Connection ($27,865 total); $42,474 combined, rendered as $42K+",
     "source": "https://artizen.fund/index/p/sturbon-mental-health-for-african-youth?season=7 (Fund submissions for season 7: 2 Curated badges); https://artizen.fund/index/mf/community-network-fund?season=7 (Competition list, $14,609 Total); https://artizen.fund/index/mf/technopenuriaphobia-fund-for-human-connection?season=7 ($27,865 Total)", "as_of": AS_OF},
    {"id": "decentralised-subscribers", "value": "24,000+ subscribers", "source": "https://www.decentralised.co/about", "as_of": AS_OF},
    {"id": "rootward-version", "value": "v0.2.1 (latest release, 2026-08-19)", "source": "https://github.com/owizdom/rootward/releases", "as_of": AS_OF},
    {"id": "gatekeeper-tests", "value": "168 tests (README: npm test)", "source": "https://github.com/owizdom/gatekeeper#readme", "as_of": AS_OF},
    {"id": "eigencompute-deep-dive-views", "value": "7,731 views (7.7K)", "source": "https://x.com/oxwizzdom/status/2050988506197950467", "as_of": AS_OF},
    {"id": "eigencompute-deep-dive-quote", "value": "4,375 views", "source": "https://x.com/eigencloud/status/2051737740090466584", "as_of": AS_OF},
    {"id": "mev-deep-dive-words", "value": "10,774 words", "source": "https://parallelresearch.substack.com/api/v1/archive", "as_of": AS_OF},
    {"id": "flashbots-forum-views", "value": "401 views on The 6.99% without PBS, 1,234 views across 6 topics",
     "source": "https://collective.flashbots.net/topics/created-by/wisdom.json", "as_of": AS_OF},
]
